#!/bin/bash 
#
# If handle parameters automatically is difficult, pass them as parameters!
#
# Otherwise:
# echo 'http://www.example.com/index.php' | grep -o '[^/]*' | wc -l
# Last / is the pagename, the rest the base URL
#
# echo 'http://www.example.com/index.php' | grep -o '[^\.]*' | wc -l
# Last point is the extension
#
# (c) spinfoo


# CEWL=../CeWL/



if [ $# -lt 2 ] ; then
	echo "Usage $0 <BASEURL> <PAGENAME> [<PAGENAME> <...>]"
	echo "Example: $0 http://www.example.com/admin index.php"
	exit
fi


UA="Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0"
BASEURL=$1
PAGENAME=$2
CURL="curl --insecure"

echo "BOB INJECT v1.3"
echo "[*] Injecting into $BASEURL..."
echo

# Use $BASEURL
for i in $(cat db_files db_dirs db_shortnames | grep -v ^#)
do
	# echo $BASEURL/$i
	($CURL -A $UA -I "$BASEURL/$i") 2> /dev/null | head -1 | grep -v 404
	if [ $? == 0 ] ; then
		echo "[*] $BASEURL/$i"
	fi
done


## for (($i=2; $i < $#-2; $i++))
## do
## PAGENAME=$i

# Use $BASEURL/$PAGENAME
for i in $(cat db_suffixes_app db_suffixes_sub | grep -v ^#) ; do
	# echo "$BASEURL/$PAGENAME$i"
	($CURL -A $UA -I "$BASEURL/$PAGENAME$i") 2> /dev/null | head -1 | grep -v 404
	if [ $? == 0 ] ; then
		echo "[*] $BASEURL/$PAGENAME$i"
	fi
done

# Use http://www.example.com/index.
EXT=$(echo -n $PAGENAME | cut -d'.' -f2)
for i in $(cat db_suffixes_sub db_suffixes_app | grep -v ^#) ; do
	PREF=$BASEURL/$(echo $PAGENAME | sed "s/\.$EXT//g")
	# echo $PREF$i
	($CURL -A $UA -I "$PREF$i") 2> /dev/null | head -1 | grep -v 404
	if [ $? == 0 ] ; then
		echo "[*] $PREF$i"
	fi
done
## done
